name = "shop-nuxt"
type = "javascript"
account_id = "__ACCOUNT_ID__"
workers_dev = true
route = ""
zone_id = "__ZONE_ID__"
main = ".output/server/index.mjs"
compatibility_date = "2021-12-17"

[site]
bucket = ".output/public"
entry-point = ".output"

[build]
command = ""

[build.upload]
format = "service-worker"
